@startuml
left to right direction
actor "IoT Device (ESP32)" as Device
actor "Pelayan / Admin" as User

rectangle "Sistem Simore (Motion Only)" {
    usecase "Kirim Data Gerakan" as UC1
    usecase "Update Status Otomatis\n(Occupied/Available)" as UC2
    usecase "Monitoring Dashboard\n(Real-time)" as UC3
    usecase "Lihat Status Okupansi\n(Merah/Hijau)" as UC4
    usecase "Deteksi Ghost Booking\n(No-Show Alert)" as UC5
    usecase "Terima Notifikasi\n(Meja Kosong/Dirty)" as UC6
    usecase "Kelola Reservasi Meja" as UC7
}

Device --> UC1
UC1 ..> UC2 : <<include>>
UC2 --> UC3 : triggers info
UC3 ..> UC4 : <<include>>
User --> UC3
User --> UC7
User --> UC6

' Ghost Booking Logic
UC5 .> UC7 : <<extend>>
UC5 --> UC6 : triggers alert

@enduml